{% set pyproject = load_file_data('pyproject.toml') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}
{% set description = pyproject.get('project', {}).get('description') %}

{% set major = load_file_regex(
  load_file="src/openalea/spice/version.py",
  regex_pattern='major = (.+)') %}
{% set minor = load_file_regex(
  load_file="src/openalea/spice/version.py",
  regex_pattern='minor = (.+)') %}
{% set post = load_file_regex(
  load_file="src/openalea/spice/version.py",
  regex_pattern='post = (.+)') %}

{% set version = major[1]+'.'+minor[1]+'.'+post[1] %}


package:
  name: openalea.spice
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  script_env:
    - CMAKE_GEN=Visual Studio 15 2017 # [win]
    - CMAKE_GENERATOR=Visual Studio 15 2017 # [win]
    - CXX=cl.exe # [win]
    - CC=cl.exe # [win]
    - cxx_compiler=cl.exe # [win]
    - c_compiler=cl.exe # [win]
  script:
    - {{PYTHON}} -m pip install . -vv

requirements:
  host:
    - python x.x
    - numpy x.x
    - nanobind-abi
    - nanobind
    - pybind11-abi # [unix]
    - scikit-build-core
    - scipy

  build:
    - {{ compiler("cxx") }}
    - python x.x
    - numpy x.x
    - scikit-build-core
    - scipy
    - make
    - cmake
    - ninja
    - nanobind
    - pybind11 # [unix]
    - embree
    - llvm-openmp
    - tbb
    - tbb-devel

  run:
    - python x.x
    - numpy x.x
    - jupyterlab
    - openalea.plantgl
    - openalea.lpy
    - oawidgets
    - ipywidgets
    - nanobind
    - pandas
    - embree
    - matplotlib
    - pywin32 [win]

test:
  imports:
    - openalea.spice
    - openalea.spice.common
    - openalea.spice.energy
    - openalea.spice.loader
    - openalea.spice.reader
    - openalea.spice.simulator
  requires:
    - pytest
  source_files:
    - tests/**
  commands:
    - pytest

about:
  home: {{ home }}
  summary: {{ description }}
