{% set pyproject = load_file_data('pyproject.toml') %}
{% set version = pyproject.get('project', {}).get('version') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}
{% set description = pyproject.get('project', {}).get('description') %}
package:
  name: openalea.spice
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  script_env:
    - CMAKE_GEN=MinGW Makefiles # [win]
    - CMAKE_GENERATOR=MinGW Makefiles # [win]
    - CXX=g++ # [win]
    - CC=gcc # [win]
    - cxx_compiler=g++ # [win]
    - c_compiler=gcc # [win]
  script:
    - {{PYTHON}} -m pip install . -vv

requirements:
  host:
    - python x.x
    - numpy x.x
    - nanobind-abi
    - nanobind
    - pybind11-abi # [unix]
    - scikit-build-core
    - scipy

  build:
    - {{ compiler("cxx") }}
    - python x.x
    - numpy x.x
    - scikit-build-core
    - scipy
    - make
    - cmake
    - gcc   # [win]
    - ninja
    - nanobind
    - pybind11 # [unix]
    - embree
    - llvm-openmp
    - tbb
    - tbb-devel

  run:
    - python x.x
    - numpy x.x
    - jupyterlab
    - openalea.plantgl
    - openalea.lpy
    - oawidgets
    - ipywidgets
    - nanobind
    - pandas
    - embree
    - matplotlib
    - pywin32 [win]

test:
  imports:
    - openalea.spice
    - openalea.spice.common
    - openalea.spice.energy
    - openalea.spice.loader
    - openalea.spice.reader
    - openalea.spice.simulator
  requires:
    - pytest
  source_files:
    - tests/**
  commands:
    - pytest

about:
  home: {{ home }}
  summary: {{ description }}
