{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set name = pyproject.get('project').get('name') %}
{% set description = pyproject.get('project').get('description') %}
{% set version = environ.get('SETUPTOOLS_SCM_PRETEND_VERSION', "0.0.0.dev") %}
{% set home = pyproject.get('project', {}).get('urls', {}).get('Homepage', '') %}
{% set build_deps = pyproject.get("build-system", {}).get("requires", []) %}
{% set deps = pyproject.get('project', {}).get('dependencies', []) %}
{% set conda_deps = pyproject.get('tool', {}).get('conda', {}).get('environment', {}).get('dependencies',[]) %}
{% set test_deps = pyproject.get('project', {}).get('optional-dependencies', {}).get('test',[]) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  string: py{{ PY_VER }}
  script_env:
    - CMAKE_GEN=Visual Studio 15 2017 # [win]
    - CMAKE_GENERATOR=Visual Studio 15 2017 # [win]
    - CXX=cl.exe # [win]
    - CC=cl.exe # [win]
    - cxx_compiler=cl.exe # [win]
    - c_compiler=cl.exe # [win]
  script:
    - {{PYTHON}} -m pip install . -vv

requirements:
  host:
    - python
    - numpy
    - nanobind-abi
    - nanobind
    - pybind11-abi # [unix]
    - scikit-build-core
    - setuptools-scm
    - vs2017_win-64 # [win]
    - scipy

  build:
    - {{ compiler("cxx") }}
    - python
    - scikit-build-core
    - setuptools-scm
    - scipy
    - make
    - cmake
    - ninja
    - vs2017_win-64 # [win]
    - nanobind
    - pybind11 # [unix]
    - embree
    - llvm-openmp
    - tbb
    - tbb-devel

  run:
    - python
    - openalea.plantgl
    - nanobind
    - pandas
    - openpyxl
    - matplotlib
    - scipy
    - embree
    - pywin32 [win]

test:
  imports:
    - openalea.spice
    - openalea.spice.common
    - openalea.spice.energy
    - openalea.spice.loader
    - openalea.spice.reader
    - openalea.spice.simulator
  requires:
    - pytest
  source_files:
    - tests/**
  commands:
    - pytest

about:
  summary: {{ pyproject["project"]["description"] }}
  license-file:
    - LICENSE
    - src/cpp/LICENSE
  home: {{ pyproject["project"]["urls"]["Homepage"] }}
